import { useEffect, useRef, useState, useCallback } from 'react'
import { useNavigate } from 'react-router-dom'
import jsQR from 'jsqr'
import { toast } from 'sonner'
import {
  QrCode,
  Camera,
  CheckCircle2,
  AlertCircle,
  RefreshCw,
} from 'lucide-react'
import { useImpersonation } from '../../../app/ImpersonationContext'
import { getEquipment, listEquipment } from '../../../services/equipmentService'
import { Button } from '../../../components/ui/button'
import PageHeader from '../../../components/PageHeader'

type ScanStatus = 'starting' | 'scanning' | 'found' | 'error' | 'not_found' | 'no_camera'

const navy = '#1A4889'

export default function QRScannerPage() {
  const navigate = useNavigate()
  const { effectiveRole } = useImpersonation()

  const [status, setStatus] = useState<ScanStatus>('starting')
  const [statusMessage, setStatusMessage] = useState('Initializing camera…')

  const videoRef = useRef<HTMLVideoElement>(null)
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const streamRef = useRef<MediaStream | null>(null)
  const rafRef = useRef<number | null>(null)
  const hasProcessed = useRef(false)

  // ── Navigation ─────────────────────────────────────────────────────────────
  const navigateToEquipment = useCallback(
    (id: string) => {
      if (effectiveRole === 'admin') navigate(`/admin/equipment/${id}`)
      else if (effectiveRole === 'field') navigate(`/field/equipment/${id}`)
      else if (effectiveRole === 'maintenance') navigate(`/maintenance/equipment/${id}`)
      else navigate(`/admin/equipment/${id}`)
    },
    [effectiveRole, navigate],
  )

  // ── QR decode handler ───────────────────────────────────────────────────────
  const handleCode = useCallback(
    async (decodedText: string) => {
      if (hasProcessed.current) return
      hasProcessed.current = true

      // Stop scanning frames
      if (rafRef.current !== null) {
        cancelAnimationFrame(rafRef.current)
        rafRef.current = null
      }

      setStatus('found')
      setStatusMessage('QR Code detected — looking up equipment…')

      // Try by ID first (QR codes generated by EquipTrack encode the equipment ID)
      // then fall back to searching by asset tag
      let equipment = null
      try {
        equipment = await getEquipment(decodedText)
      } catch {
        /* not found by ID */
      }
      if (!equipment) {
        try {
          const results = await listEquipment({ search: decodedText })
          if (results.length > 0) equipment = results[0]
        } catch {
          /* search failed */
        }
      }

      if (!equipment) {
        setStatus('not_found')
        setStatusMessage('No equipment found for this QR code. Try scanning again.')
        hasProcessed.current = false
        return
      }

      toast.success(`Found: ${equipment.name}`)
      navigateToEquipment(equipment.id)
    },
    [navigateToEquipment],
  )

  // ── Scan loop ───────────────────────────────────────────────────────────────
  const tick = useCallback(() => {
    const video = videoRef.current
    const canvas = canvasRef.current
    if (!video || !canvas || hasProcessed.current) return

    if (video.readyState >= video.HAVE_ENOUGH_DATA) {
      const ctx = canvas.getContext('2d', { willReadFrequently: true })
      if (!ctx) return

      canvas.width = video.videoWidth
      canvas.height = video.videoHeight
      ctx.drawImage(video, 0, 0, canvas.width, canvas.height)

      const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height)
      const code = jsQR(imageData.data, imageData.width, imageData.height, {
        inversionAttempts: 'dontInvert',
      })

      if (code?.data) {
        handleCode(code.data)
        return // don't schedule next frame
      }
    }

    rafRef.current = requestAnimationFrame(tick)
  }, [handleCode])

  // ── Start camera ────────────────────────────────────────────────────────────
  const startCamera = useCallback(async () => {
    hasProcessed.current = false
    setStatus('starting')
    setStatusMessage('Initializing camera…')

    // Stop any existing stream
    if (streamRef.current) {
      streamRef.current.getTracks().forEach((t) => t.stop())
      streamRef.current = null
    }
    if (rafRef.current !== null) {
      cancelAnimationFrame(rafRef.current)
      rafRef.current = null
    }

    if (!navigator.mediaDevices?.getUserMedia) {
      setStatus('no_camera')
      setStatusMessage('Camera access is not supported in this browser.')
      return
    }

    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'environment', width: { ideal: 1280 }, height: { ideal: 720 } },
      })
      streamRef.current = stream

      const video = videoRef.current
      if (video) {
        video.srcObject = stream
        video.setAttribute('playsinline', 'true') // required for iOS
        await video.play()
        setStatus('scanning')
        setStatusMessage('Point your camera at an equipment QR code')
        rafRef.current = requestAnimationFrame(tick)
      }
    } catch (err: unknown) {
      const name = err instanceof Error ? err.name : ''
      if (name === 'NotAllowedError' || name === 'PermissionDeniedError') {
        setStatus('no_camera')
        setStatusMessage('Camera permission denied. Allow camera access in your browser and try again.')
      } else {
        setStatus('error')
        setStatusMessage('Could not start the camera. Make sure a camera is connected and try again.')
      }
    }
  }, [tick])

  // ── Mount / unmount ─────────────────────────────────────────────────────────
  useEffect(() => {
    startCamera()
    return () => {
      if (rafRef.current !== null) cancelAnimationFrame(rafRef.current)
      if (streamRef.current) streamRef.current.getTracks().forEach((t) => t.stop())
    }
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  // ── Status bar config ───────────────────────────────────────────────────────
  const statusConfig: Record<ScanStatus, { bar: string; text: string; icon: React.ReactNode }> = {
    starting: {
      bar: 'bg-slate-50 border-slate-200',
      text: 'text-slate-600',
      icon: <QrCode className="h-4 w-4 shrink-0" />,
    },
    scanning: {
      bar: 'bg-blue-50 border-blue-200',
      text: 'text-blue-700',
      icon: <Camera className="h-4 w-4 shrink-0 animate-pulse" />,
    },
    found: {
      bar: 'bg-green-50 border-green-200',
      text: 'text-green-700',
      icon: <CheckCircle2 className="h-4 w-4 shrink-0" />,
    },
    error: {
      bar: 'bg-red-50 border-red-200',
      text: 'text-red-700',
      icon: <AlertCircle className="h-4 w-4 shrink-0" />,
    },
    not_found: {
      bar: 'bg-amber-50 border-amber-200',
      text: 'text-amber-700',
      icon: <AlertCircle className="h-4 w-4 shrink-0" />,
    },
    no_camera: {
      bar: 'bg-red-50 border-red-200',
      text: 'text-red-700',
      icon: <AlertCircle className="h-4 w-4 shrink-0" />,
    },
  }

  const cfg = statusConfig[status]
  const showRetry = status === 'error' || status === 'not_found' || status === 'no_camera'

  return (
    <div className="space-y-6 pb-10">
      <PageHeader
        title="QR Code Scanner"
        subtitle="Scan an equipment QR code to instantly open its profile"
      />

      <div className="max-w-lg mx-auto space-y-4">
        {/* Status bar */}
        <div className={`flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium border ${cfg.bar} ${cfg.text}`}>
          {cfg.icon}
          <span>{statusMessage}</span>
        </div>

        {/* Camera viewport */}
        <div className="overflow-hidden rounded-xl border border-slate-200 shadow-sm">
          <div className="relative bg-slate-900 overflow-hidden" style={{ minHeight: 340 }}>

              {/* Live video feed */}
              <video
                ref={videoRef}
                className="w-full h-full object-cover"
                muted
                playsInline
              />

              {/* Hidden canvas used only for frame analysis */}
              <canvas ref={canvasRef} className="hidden" />

              {/* Starting overlay */}
              {status === 'starting' && (
                <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 text-white bg-slate-900">
                  <QrCode className="h-14 w-14 opacity-20 animate-pulse" />
                  <p className="text-sm text-white/50">Starting camera…</p>
                </div>
              )}

              {/* Error overlay */}
              {showRetry && (
                <div className="absolute inset-0 flex flex-col items-center justify-center gap-4 bg-slate-900 px-6">
                  <AlertCircle className="h-12 w-12 text-red-400 opacity-60" />
                  <p className="text-sm text-white/60 text-center leading-relaxed">{statusMessage}</p>
                </div>
              )}

              {/* Scanning crosshair (shows only while active) */}
              {status === 'scanning' && (
                <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                  <div className="relative" style={{ width: 260, height: 260 }}>
                    {/* corner TL */}
                    <span className="absolute top-0 left-0 w-6 h-6 border-t-2 border-l-2 border-white rounded-tl" />
                    {/* corner TR */}
                    <span className="absolute top-0 right-0 w-6 h-6 border-t-2 border-r-2 border-white rounded-tr" />
                    {/* corner BL */}
                    <span className="absolute bottom-0 left-0 w-6 h-6 border-b-2 border-l-2 border-white rounded-bl" />
                    {/* corner BR */}
                    <span className="absolute bottom-0 right-0 w-6 h-6 border-b-2 border-r-2 border-white rounded-br" />
                  </div>
                </div>
              )}

              {/* Found flash */}
              {status === 'found' && (
                <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 bg-green-900/70">
                  <CheckCircle2 className="h-14 w-14 text-green-300" />
                  <p className="text-sm text-green-100 font-medium">Equipment found!</p>
                </div>
              )}
          </div>
        </div>

        {/* Retry button */}
        {showRetry && (
          <div className="flex justify-center">
            <Button onClick={startCamera} style={{ backgroundColor: navy }} className="gap-2">
              <RefreshCw className="h-4 w-4" />
              Try Again
            </Button>
          </div>
        )}

        {/* Instructions */}
        <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
          <div className="border-b border-slate-100 bg-slate-50 px-4 py-2.5">
            <p className="text-[11px] font-semibold uppercase tracking-widest text-slate-400 flex items-center gap-1.5">
              <QrCode className="h-3.5 w-3.5" />
              How to scan
            </p>
          </div>
          <div className="p-4">
            <ol className="text-sm text-slate-600 space-y-3">
              {[
                'Allow camera access when your browser asks.',
                'Hold the camera steady over any equipment QR code.',
                "EquipTrack will navigate to that equipment's profile automatically.",
              ].map((step, i) => (
                <li key={i} className="flex items-start gap-3">
                  <span className="shrink-0 mt-0.5 flex h-5 w-5 items-center justify-center rounded-full bg-slate-100 text-[11px] font-bold text-slate-600">
                    {i + 1}
                  </span>
                  <span className="leading-relaxed">{step}</span>
                </li>
              ))}
            </ol>
            <p className="mt-4 text-xs text-slate-400 border-t border-slate-100 pt-3">
              Tip: QR codes can be downloaded from each equipment's profile page and printed for physical tagging.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
